# Generated by Django 3.2.18 on 2023-05-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='RESTO_TABLE',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.resto_table'),
        ),
    ]
